name: Convert README

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Ignore Invalid Images
        run: echo "function Image(el) return pandoc.Str('[Image]') end" > ignore-images.lua

      - name: Convert README to PDF and DOCX
        run: |
          mkdir -p doc
          pandoc README.md -o doc/README.pdf --lua-filter=ignore-images.lua
          pandoc README.md -o doc/README.docx
